version: "3"

services:
  app:
    build: .
    container_name: springboot-config-and-secrets-managed-by-doppler
    environment: 
      - APP_NAME=${APP_NAME}
      - APP_SECRET=${APP_SECRET}
      - APP_API_KEY=${APP_API_KEY}
    ports:
      - "8080:8080"