version: "3"

services:
  app:
    build: .
    container_name: springboot-config-and-secrets-managed-by-doppler
    environment: 
      - APP_NAME
      - APP_SECRET
      - APP_CUSTOMPROPERTY
    ports:
      - "8080:8080"
